//! Verifies the Rust xBRZ port is bit-for-bit identical to the reference C++
//! implementation (Zenju's xBRZ, GPL-licensed) using golden fixtures.
//!
//! The fixtures in `fixtures/xbrz_reference.txt` were generated by compiling
//! the reference `xbrz.cpp` (with its default `ScalerCfg`) and dumping the
//! raw ARGB output for the two patterns in `tests/common/mod.rs` at every
//! scale factor 2x–6x. The fixture generator itself is kept outside the repo;
//! only the numeric output (facts) is committed.

mod common;

use std::collections::HashMap;

use xbrztrace::xbrz_engine::{scale_image, Argb, ArgbImage, ScalerConfig};

/// Parse the fixture file into a map of (pattern name, factor) -> raw ARGB.
fn parse_fixtures(text: &str) -> HashMap<(String, u8), Vec<u32>> {
    let mut out = HashMap::new();
    let mut pattern = String::new();
    let mut factor = 0u8;
    let mut remaining = 0usize;
    let mut buf = Vec::new();

    for line in text.lines() {
        if let Some(name) = line.strip_prefix("PATTERN ") {
            pattern = name.to_string();
        } else if let Some(f) = line.strip_prefix("FACTOR ") {
            factor = f.parse().unwrap();
            remaining = (8 * factor as usize).pow(2);
            buf.clear();
        } else if remaining > 0 {
            buf.push(u32::from_str_radix(line.trim(), 16).unwrap());
            remaining -= 1;
            if remaining == 0 {
                out.insert((pattern.clone(), factor), buf.clone());
            }
        }
    }
    assert!(!out.is_empty(), "fixture file parsed nothing");
    out
}

fn count_lines(text: &str) -> usize {
    text.lines().count()
}

#[test]
fn port_matches_reference_bit_exactly() {
    let fixtures = include_str!("fixtures/xbrz_reference.txt");
    let expected = parse_fixtures(fixtures);

    // Sanity: the fixture file must contain both patterns at all 5 factors.
    assert_eq!(expected.len(), 2 * 5, "unexpected fixture content");
    assert!(count_lines(fixtures) > 10_000);

    let cases: [(&str, ArgbImage); 2] = [
        ("diag", common::pattern_diag()),
        ("mix", common::pattern_mix()),
    ];

    for (name, img) in cases {
        for factor in 2..=6u8 {
            let out = scale_image(&img, factor, &ScalerConfig::default());
            let want = expected
                .get(&(name.to_string(), factor))
                .unwrap_or_else(|| panic!("missing fixture for {name} at {factor}x"));
            assert_eq!(
                out.pixels.len(),
                want.len(),
                "dimension mismatch for {name} at {factor}x"
            );
            for (i, (&got, &want_px)) in out.pixels.iter().zip(want.iter()).enumerate() {
                assert_eq!(
                    got.0, want_px,
                    "pixel {i} of pattern {name} at {factor}x differs from reference"
                );
            }
        }
    }
}

#[test]
fn fixture_pixels_are_valid_argb() {
    // Spot-check the fixture parsing produces sane colors (alpha in top byte).
    let fixtures = include_str!("fixtures/xbrz_reference.txt");
    let expected = parse_fixtures(fixtures);
    let some = expected.get(&("diag".to_string(), 4u8)).unwrap();
    assert_eq!(some.len(), (8usize * 4).pow(2));
    let argb = Argb(some[0]);
    let _ = (argb.a(), argb.r(), argb.g(), argb.b());
}
